### ISSUE TITLE
about CMSG_DB_QUERY_BULK

### ISSUE THREAD

**Issue by ghost** [Konctantin/FakePacketSender#2]
When i use entry = 1, i found that < [0] Entry: 65536>.  why?

ClientToServer: CMSG_DB_QUERY_BULK (0x138B) Length: 14 ConnIdx: 0 Time: 02/17/2015 09:34:30.841 Number: 2968
DB2 File: BroadcastText (35137211)
Count: 1
Guid: Full: 0x0
[0] Entry: 65536
Packet not fully read! Current position: 12 Length: 14 Bytes remaining: 2.
|-------------------------------------------------|---------------------------------|
| 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F | 0 1 2 3 4 5 6 7 8 9 A B C D E F |
|-------------------------------------------------|---------------------------------|
| BB 26 18 02 00 08 00 00 00 00 01 00 00 00       | . & . . . . . . . . . . . .     |
|-------------------------------------------------|---------------------------------|

``` sql
local sendOffset = 0x69D0;
local CMSG_DB_QUERY_BULK = 0x138B;
local packet = CreateFakePacket(sendOffset, CMSG_DB_QUERY_BULK);
print("Start CMSG_DB_QUERY_BULK");
local entry = 1;
while entry < 10000 do
    -- for i = 1, math.random(1,2) do
        packet:Clear();
        packet:WriteInt32(35137211); -- BroadcastText
        packet:WriteBits(1,13); -- Count
        packet:WriteInt32(0x0); -- Guid
        packet:WriteInt32(entry); -- entry
        packet:Send();
        entry = entry + 1;
    --end
    print(string.format("Send Entry: %d, Dump: %s", entry, packet:Dump()));
    sleep(100);
end
print("Done!");
```

**Comment by Konctantin** [comment]
because the incorrect packet structure:

field
packet:WriteInt32(0x0); -- Guid (you wrote 4 bytes)

if you want to record as null guid
it is necessary to write so

packet:WriteBytes(0,0); -- 2-byte GUID is a mask value

**Comment by ghost** [comment]
thx
