### ISSUE TITLE
запуск

### ISSUE THREAD

**Issue by soulfrost** [Konctantin/FakePacketSender#3]
скомпилировалось нормально, но отказывается запускаться под вин 10 ( совместимость с вин 7 стоит ) - нужны какие-то особые махинации что-бы запустить?

**Comment by Konctantin** [comment]
Никакой совместимости не надо (проверено на Win7,Win8,Win10TP).
Обязательное условие запуска - наличие запущеного процесса Wow.exe

**Comment by soulfrost** [comment]
32 битный?
