### ISSUE TITLE
гуид

### ISSUE THREAD

**Issue by soulfrost** [Konctantin/FakePacketSender#5]
есть ли способ писать гуид? 
полистал сорцы, но не нашел метода... 
по идее можно составить таблицу айдишников карт и адресов допустим для 1 из реалмов, и бить перебором по ним - да, будет долго, но за-то будет работать... или всё же я глубого ошибаюсь и всю инфу для этого не собрать

**Comment by Konctantin** [comment]
GUID можно записать как последовательность байт, либо же написать функцию записи GUIDа в самом скрипте. Для этого там есть API для работы с побитовыми операциями.
